### ISSUE TITLE
initially it works complie but now i dowmloaded new file im  getting error

### ISSUE THREAD

**Issue by cybercortar** [EVLF/Cypher-Rat-Source-Code#36]
initial it works but now it's getting error
![image](https://user-images.githubusercontent.com/82813920/176481059-551d5b58-8a31-4143-a6d7-ccae816709c2.png)

**Comment by EVLF** [comment]
Download compiled version and copy res folder next to the exe

**Comment by cybercortar** [comment]
can you be more specific sir, still getting same error.

**Comment by cybercortar** [comment]
i dont know you why i m getting but 2 last files you posted were doing prefect then i over write with latest files and now I'm getting this error

these two error are poping up:

     System.InvalidOperationException: 'An error occurred creating the form. See Exception.InnerException for details.  The error is: The type initializer for 'AngelAndroid_v2.sockets.Data' threw an exception.'
 1:                                     **TypeInitializationException: The type initializer for 'AngelAndroid_v2.sockets.Data' threw an exception.**

2:  **DirectoryNotFoundException: Could not find a part of the path 'C:\Users\YBERCORTAR\OneDrive\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\bin\Debug\bin\debug\'.**

**Comment by cybercortar** [comment]
i debuged and got error removved thanks sir,thank you
