### ISSUE TITLE
Compile error, Need Help

### ISSUE THREAD

**Issue by Frido-Cpp** [EVLF/Cypher-Rat-Source-Code#43]
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30456	'AngelAndroidForm' is not a member of 'AngelAndroid_v2'.	AngelAndroid	C:\Users\User\Desktop\Cypher-Rat-Source-Code-main\AngelAndroid\My Project\Application.Designer.vb	35	N/A

**Comment by WhitteGoose** [comment]
bro check README.md of this repo, there is solution to this problem

**Comment by Frido-Cpp** [comment]
okay bro
