### ISSUE TITLE
Camera not working on injector

### ISSUE THREAD

**Issue by vstreamstack** [EVLF/Cypher-Rat-Source-Code#48]
report bug injector, camera not working

**Comment by EVLF** [comment]
the injection is dependable , it depend on the injected app permissions

**Comment by linggarseptian** [comment]
![image](https://user-images.githubusercontent.com/76572685/184059847-cf0cf0db-6aae-48d6-a231-47755d173dac.png)

my app permission, camera still not working

**Comment by vstreamstack** [comment]
any fix for this bug?
