### ISSUE TITLE
Why the update.apk download bro?, Also seen in apk source

### ISSUE THREAD

**Issue by Frido-Cpp** [EVLF/Cypher-Rat-Source-Code#54]
![Screenshot 2022-08-13 181633](https://user-images.githubusercontent.com/74474880/184504279-2478e61d-11fd-472d-9ac9-a64d3e051304.png)

**Comment by linggarseptian** [comment]
trying install .update.apk on download folder is another cypherRat.apk

**Comment by Frido-Cpp** [comment]
Cruel.  I discoverd that on the apk source too and downloads as hidden.

**Comment by EVLF** [comment]
![image](https://user-images.githubusercontent.com/54191699/184510598-c35ca112-614a-4293-910f-55135e925302.png)


cypher rat have this feature . called " Download APK" using direct apk link , and this function handle 

try use this function and you will see what i mean

**Comment by EVLF** [comment]
> trying install .update.apk on download folder is another cypherRat.apk

don't lie , just follow the function calls and you will understand , if you are developer i mean

**Comment by Frido-Cpp** [comment]
Okay Verified
