### ISSUE TITLE
Auto Start Not Working After Clear Ram

### ISSUE THREAD

**Issue by Dark-Agent-x** [EVLF/Cypher-Rat-Source-Code#56]
Hi Brother,
I test your all versions but latest version is not stable because when I clear my ram app crashed and when I open app in app manager so I can easy clear all data when I clear data so app automatically stopped running but your previous version when we click on clear data it get back to us. accessibility force not so aggressive when we back it will come very late. kindly update it like previous one and also add autostarter helper in this latest version. hope this suggest will help you to update and make more stable program. Thank you.

**Comment by EVLF** [comment]
ok bro , no problem I will recheck that
