### ISSUE TITLE
Alternatives for Linux

### ISSUE THREAD

**Issue by ChillVibesMushroom** [EVLF/Cypher-Rat-Source-Code#60]
I'm looking for something like Cypher Rat for Linux I really like this idea but I don't want to split away from my OS what are my.options team. Besides msf.

**Comment by indian-crew** [comment]
U can use AIRAVAT RAT BY PRATEEK CHAUBEY @theoneandonly on github. It's a server or browser based RAT and it will work on  every OS bcoz it's a browser based RAT.

**Comment by EVLF** [comment]
there is a lot of options , first option is Metasploit
