### ISSUE TITLE
Building resources

### ISSUE THREAD

**Issue by DOK2141** [EVLF/Cypher-Rat-Source-Code#61]
This is where the process stops. What could be the reason?
![Screenshot_1](https://user-images.githubusercontent.com/114049835/192010616-00f05549-ba70-443c-a30e-b055538f37c4.png)

**Comment by EVLF** [comment]
Try this options:

1- install java SDK: go [HERE](https://www.oracle.com/java/technologies/downloads/#jdk19-windows) , and download and install "x64 Installer"

2- Disable Windows Defender and try again

3- Press Win + R , Enter "%LocalAppData%" , windows explorer with open , Search for Folder named apktool open it , then framework , and you will find file named 1.apk remove it and try again
